# Generated by Django 3.0.2 on 2020-01-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(default=None, max_length=255)),
                ('benefit', models.CharField(default=None, max_length=255)),
                ('currency', models.CharField(default=None, max_length=255)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(editable=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_user_id', models.CharField(default=None, max_length=255)),
                ('benefit', models.CharField(default=None, max_length=255)),
                ('currency', models.CharField(default=None, max_length=255)),
                ('total_max_amount', models.FloatField()),
            ],
            options={
                'unique_together': {('external_user_id', 'benefit', 'currency')},
            },
        ),
    ]
